### PR TITLE
Rebase onto dthree/master - Closes #21

### LINKED ISSUE #21: Update to include latest changes from original repo

### PR DESCRIPTION
**Pull request by willclarktech**
Rebases our `master` branch onto the original project as of https://github.com/dthree/vorpal/commit/2073ad9d77b02a05b86f122ef473a10f164e43ba

I believe that version is `1.12.0` as published on npm, but release management is inconsistent on the vorpal project so it's difficult to tell.

Summary of changes:
- Exit event: https://github.com/LiskHQ/vorpal/pull/20/commits/c44e36aba26765e15435d898b4c6fc42751435f1
- A feature for extending commands: https://github.com/LiskHQ/vorpal/pull/20/commits/f8d6f95beb510fdbd70057689ee122612f7f85a5
- `name` is renamed `title`: https://github.com/LiskHQ/vorpal/pull/20/commits/e1e296f932359ff3e5f55624aeea38df09f35716
- New setters for the instance: https://github.com/LiskHQ/vorpal/pull/20/commits/58b4077b9d60ab41554cc7996fefb9623e5d5f3f
- Logic for building a header whatever that is: https://github.com/LiskHQ/vorpal/pull/20/commits/44b780b205415c56fa303a7357e9fb944ab2353a
- Something about autocompleting options: https://github.com/LiskHQ/vorpal/pull/20/commits/16f0f645e3d0cc63c2d463671c06ebd98c546cb4
- Bug fix for falsy variadic args: https://github.com/LiskHQ/vorpal/pull/20/commits/077543bd037a1f07d73acc944de74efc29e6da4e
- Bug fix with slashes in autocomplete options: https://github.com/LiskHQ/vorpal/pull/20/commits/9d393df6d3b264b31836e03a429bd261540172b0
- Bug fix for validation errors: https://github.com/LiskHQ/vorpal/pull/20/commits/58a4b9792b0ffb2d56037ccc5865a4039f79e0b4

Closes #21

### CODE REVIEW

**Comment by toschdev** [comment]
Do you have any insights to what value it would provide to integrate those changes?

**Comment by willclarktech** [comment]
@Tosch110 Summary of changes added to description.

**Review by toschdev — APPROVED** [review]

**Comment by willclarktech** [comment]
Tests are failing...

**Review by toschdev — DISMISSED** [review]
Tests should be passing

**Review by shuse2 — APPROVED** [review]

**Pull request merged**
